config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'

  resources :posts do 
    resources :comments
    resources :upvotes, only: :create
    resources :downvotes, only: :create
  end
  resources :users, only: :show

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
    validates :text, :user_id, :post_id, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  mount_uploader :photo, PhotoUploader
  validates :photo, :description, :user_id, presence: true
  
  acts_as_votable
  
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :photo, PhotoUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
  
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :name, :photo) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :name, :photo) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, only: :create
    before_action :is_owner?, only: :destroy
    
    def create
      @post = Post.find(params[:post_id])
      @comment = @post.comments.create(comment_params.merge(user_id: current_user.id))
      if @comment.valid?
        redirect_to root_path
      else
        flash[:alert] = "Invalid attributes."
        redirect_to root_path
      end
    end
    
    def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
      redirect_to root_path
    end
  
    private 
    
    # this method should be private
    # this logic shouldn't be exposed to other programs
    def is_owner?
      @comment = Comment.find(params[:id])
      if @comment.user != current_user
        redirect_to root_path
      end
    end
    
    def comment_params
      params.require(:comment).permit(:text, :post_id)
    end
end

app/controllers/downvotes_controller.rb
class DownvotesController < ApplicationController
before_action :authenticate_user!
    def create
        @post = Post.find(params[:post_id])
        @post.downvote_from current_user
        respond_to do |format|
            format.html { redirect_to posts_path }
            format.js {}
        end
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :destroy]
    #before_action :is_owner?, only: [:edit, :update]
    
    def new
        @post = Post.new
    end
    
    def create
        @post = current_user.posts.create(post_params)
        if @post.valid?
        redirect_to root_path
        else
        render :new, status: :unprocessable_entity
        end
    end
    
    def index
        @posts = Post.all.order('created_at DESC')
    end
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
      @post = Post.find(params[:id])
      @post.update(post_params)
      if @post.valid?
        redirect_to root_path
      else
        render :edit, status: :unprocessable_entity
      end
    end
    
    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to root_path
    end
    
    def show
      @post = Post.find(params[:id])
    end

    private
    
    def is_owner?
        redirect_to root_path if Post.find(params[:id]).user != current_user
    end
    private

    def post_params
        params.require(:post).permit(:user_id, :photo, :description)
    end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
before_action :authenticate_user!

    def create
        @post = Post.find(params[:post_id])
        @post.liked_by current_user
        respond_to do |format|
         format.html { }
         format.js {}
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/downvotes_helper.rb
module DownvotesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/downvotes/create.js.erb
$('#likes_container_<%= @post.id %>').html("<%= escape_javascript render partial: '/posts/likes', locals: { post: @post } %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Instapost</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  
</head>
<body>
<nav>
  <div class ="row">
      <div class = "col-lg-6 col-lg-offset-3">
          <div class ="row"></div>
            <div class = "nav_wapper">
                
                <div class="col-xs-6">
                  <span class ="pull-left brand">Instapost</span>
                </div>
                
                <div class="col-xs-6">
                  <% if user_signed_in? %>
                    <span class ="nav_links pull-right"><%= link_to 'New Post', new_post_path %></span>
                    <span class ="nav_links pull-right"><%= link_to 'Edit Settings', edit_user_registration_path %></span>
                    <span class ="nav_links pull-right"><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></span>
                  <% else %>
                    <span class ="nav_links pull-right"><%= link_to 'Sign Up', new_user_registration_path %>
                    <span class ="nav_links pull-right"><%= link_to 'Log In', new_user_session_path %>
                  <% end %>
                </div>
            </div>
          </div>
      </div>
  </div> 
</nav>    
  <%= yield %>
  
</body>
</html>

app/views/posts/_likes.html.erb
<% if user_signed_in? %>
  <span class="post_like">
    <% if current_user.voted_up_on? post %>
      <%= link_to '<i class="fa fa-heart" aria-hidden="true"></i>'.html_safe, post_downvotes_path(post.id), method: :post, remote: true %> 
    <% else %>
      <%= link_to '<i class="fa fa-heart-o" aria-hidden="true"></i>'.html_safe, post_upvotes_path(post.id), method: :post, remote: true  %>
    <% end %>

    <%= pluralize post.get_likes.size, "like" %>
  </span>
<% else %>
  <span class="post_like">
    <i class="fa fa-heart-o" aria-hidden="true"></i> <%= pluralize post.get_likes.size, "like" %>
  </span>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= simple_form_for @post do |f| %>
  <%= f.input :photo %>
  <%= f.input :description %>
  <%= f.submit 'Update', class: 'btn btn-default btn-block' %>
<% end %>

app/views/posts/index.html.erb
<!-- index.html.erb --> 
<% @posts.each do |post| %>
  
  <div class="post_box">

    <div class="post_header">
      <%= image_tag User.find(post.user_id).photo, class: 'prof_pic_small' %>
      <%= link_to User.find(post.user_id).name, user_path(post.user_id) %>
      <span class="timestamp pull-right"><%= distance_of_time_in_words(DateTime.now, post.created_at) %> ago</span>
    </div>

    <%= image_tag post.photo, class: 'photo' %>
    
    <div class="post_body">

      <%= link_to User.find(post.user_id).name, user_path(post.user_id) %> <%= post.description %>

    </div>

    <div class="post_comments">

      <% post.comments.each do |comment| %>

        <%= link_to User.find(comment.user_id).name,  user_path(comment.user_id) %> <%= comment.text %>

      <% end %>


      <hr>
      <!-- vote/devote -->
      <span id="likes_container_<%= post.id %>">
        <%= render partial: 'likes', locals: {post: post} %>
      </span>
      <% if user_signed_in? %> <!-- comment -->
        <%= simple_form_for Comment.new, url: post_comments_path(post), method: :post do |f| %>
          <%= f.input :text, label: 'Comment', placeholder: 'Add a comment...' %>
          <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
        <% end %>
      <% end %>
    </div>
  </div>

<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= simple_form_for @post do |f| %>
  <%= f.input :photo %>
  <%= f.input :description %>
  <%= f.submit 'Post', class: 'btn btn-default btn-block' %>
<% end %>

app/views/posts/show.html.erb
<%= image_tag @post.user.photo %>
<%= @post.user.name %>
<%= image_tag @post.photo %>
<%= @post.description %>
<% if @post.user_id == current_user.id %>
  <%= link_to 'Edit Post', edit_post_path(@post.id) %>
  <%= link_to 'Delete Post', post_path(@post.id), method: :delete %>
<% end %>

app/views/upvotes/create.js.erb
$('#likes_container_<%= @post.id %>').html("<%= escape_javascript render partial: '/posts/likes', locals: { post: @post } %>")

app/views/users/show.html.erb
<!-- users/show.html.erb -->  
<div class="prof_header">

  <div class="row">

    <div class="col-xs-4">
      <%= image_tag @user.photo, class: 'prof_pic' %>
    </div>

    <div class="col-xs-8">

      <div class="user_header">

        <div class="row">
          <div class="col-xs-6">
            <h1 class = "username"><%= @user.name %></h1>
          </div>

          <div class="col-xs-6">
            <%= link_to 'EDIT PROFILE', edit_user_registration_path(@user), class: 'user_edit_button btn btn-default' if user_signed_in? && @user == current_user %>
          </div>
        </div>  
      </div>

      <span class="count"><%= @user.posts.count %></span> posts

    </div>

  </div>

</div>


<div class="prof_post_box">

  <div class="row">

    <% @user.posts.each do |post| %>

        <div class="col-xs-6">
          <%= image_tag post.photo, class: 'prof_show' %>
        </div>

    <% end %>

  </div>
</div>